version: "3"

services:
  ui:
    image: metal3d/ng
    user: ${_UID}:${_GID}
    environment:
        ANGULAR_HOST_CHECK: "false"

    volumes:
        - ./ui:/app:Z
    depends_on:
        - api

  api:
    build: containers/api
    volumes:
        - ./app:/go/src/github.com/smileinnovation/imannotate/app:Z
        - ./api:/go/src/github.com/smileinnovation/imannotate/api:Z

    user: ${_UID}:${_GID}

    working_dir: /go/src/github.com/smileinnovation/imannotate/app
    environment:
      BIN_APP_PORT: 8000
      DB_USER: mongouser
      DB_PASS: mongopwd
      DB_HOST: database
      DB_NAME: imannotate
      DB_AUTH: admin

  database:
    image: mongo
    volumes:
        - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    privileged: true

  http:
    image: nginx:alpine
    volumes:
        - ./containers/nginx/conf.d:/etc/nginx/conf.d:Z
    ports:
        - 8080:80
    depends_on:
        - api
        - ui

volumes:
  db:
