version: "2.1"

services:
  ui:
    extends:
      file: .user.compose.yml
      service: base_config

    build: 
      context: containers/ui

    working_dir: /home/node/ui
    volumes:
      - ./ui:/home/node/ui
    command: ng serve --host=0.0.0.0
    privileged: true
    depends_on:
      - database

  api:
    extends:
      file: .user.compose.yml
      service: base_config
    build:
      context: ./containers/api

    volumes:
      - ./:/go/src/github.com/smileinnovation/imannotate

    working_dir: /go/src/github.com/smileinnovation/imannotate
    environment:
      BIN_APP_PORT: 8000
      DB_USER: mongouser
      DB_PASS: mongopwd
      DB_HOST: database
      DB_NAME: imannotate
    privileged: true

  database:
    image: mongo
    volumes:
      - db:/data/db
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: mongouser
    # MONGO_INITDB_ROOT_PASSWORD: mongopwd
    privileged: true

  http:
    image: nginx:alpine
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8080:80
    depends_on:
      - api
      - ui
    privileged: true

volumes:
  db:
